replicaCount: 1

image:
  repository: soulsseekercontainers.azurecr.io/vectorizer
  tag: "0894db5163661c53beb61e3a48eb4d51bb48fa66"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

# Kubernetes Secret automatically created
# from Azure Key Vault via SecretProviderClass
secretName: kv-secrets

# Inject all Key Vault-backed secrets as env vars
envFrom:
  - secretRef:
      name: kv-secrets

# CSI Secret Store configuration
keyVault:
  enabled: true

  secretProviderClass: vectorizer-secrets

configMapName: vectorizer-config