replicaCount: 1

image:
  repository: soulsseekercontainers.azurecr.io/vectorizer
  tag: "0894db5163661c53beb61e3a48eb4d51bb48fa66"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

# Kubernetes Secret automatically created
# from Azure Key Vault via SecretProviderClass
secretName: kv-secrets

# Inject all Key Vault-backed secrets as env vars
config:
  OpenAI__EmbeddingDeployment: "text-embedding-3-small"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  ASPNETCORE_URLS: "http://+:8080"
  OpenAI__Endpoint: "https://soulsseekersai.cognitiveservices.azure.com/"
  Cosmos__DatabaseName: "SoulSeekers"
  Cosmos__TacticalReportVectorsContainerName: "SoulSeekersTacticalReportVectors"
  Cosmos__UserTacticalReportContainerName: "SoulSeekersTacticalReports"
  UseManagedIdentity: "false"
  Cosmos__UserPostCombatDialogueContainerName: "SoulSeekersPostCombatDialogue"
  Cosmos__VectorContainer: "SoulSeekersTacticalReportVectors"

envFrom:
  - secretRef:
      name: kv-secrets
  - configMapRef:
      name: vectorizer-config

# CSI Secret Store configuration
keyVault:
  enabled: true

  secretProviderClass: vectorizer-secrets

configMapName: vectorizer-config