apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: kv-secrets
  namespace: default

spec:
  provider: azure

  secretObjects:
    - secretName: kv-secrets
      type: Opaque

      data:
        - objectName: DOTNET-RUNNING-IN-CONTAINER
          key: DOTNET_RUNNING_IN_CONTAINER

        - objectName: ASPNETCORE-URLS
          key: ASPNETCORE_URLS

        - objectName: UseManagedIdentity
          key: UseManagedIdentity

        - objectName: OpenAI--Endpoint
          key: OpenAI__Endpoint

        - objectName: OpenAI--ApiKey
          key: OpenAI__ApiKey

        - objectName: OpenAI--DeploymentName
          key: OpenAI__DeploymentName

        - objectName: OpenAI--ApiVersion
          key: OpenAI__ApiVersion

        - objectName: Cosmos--ConnectionString
          key: Cosmos__ConnectionString

        - objectName: Cosmos--DatabaseName
          key: Cosmos__DatabaseName

        - objectName: Cosmos--UserPostCombatDialogueContainerName
          key: Cosmos__UserPostCombatDialogueContainerName

        - objectName: Cosmos--UserTacticalReportContainerName
          key: Cosmos__UserTacticalReportContainerName

        - objectName: Cosmos--TacticalReportVectorsContainerName
          key: Cosmos__TacticalReportVectorsContainerName

  parameters:
    keyvaultName: kv-aks-prod-argocd
    tenantId: "92b1c82c-10a6-40ec-8b2e-1e63eeb29438"

    objects: |
      array:
        - |
          objectName: DOTNET-RUNNING-IN-CONTAINER
          objectType: secret

        - |
          objectName: ASPNETCORE-URLS
          objectType: secret

        - |
          objectName: UseManagedIdentity
          objectType: secret

        - |
          objectName: OpenAI--Endpoint
          objectType: secret

        - |
          objectName: OpenAI--ApiKey
          objectType: secret

        - |
          objectName: OpenAI--DeploymentName
          objectType: secret

        - |
          objectName: OpenAI--ApiVersion
          objectType: secret

        - |
          objectName: Cosmos--ConnectionString
          objectType: secret

        - |
          objectName: Cosmos--DatabaseName
          objectType: secret

        - |
          objectName: Cosmos--UserPostCombatDialogueContainerName
          objectType: secret

        - |
          objectName: Cosmos--UserTacticalReportContainerName
          objectType: secret

        - |
          objectName: Cosmos--TacticalReportVectorsContainerName
          objectType: secret