{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: feedback

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

    external-dns.alpha.kubernetes.io/hostname: kubernetes.soulsseeker.com

    nginx.ingress.kubernetes.io/limit-rpm: {{ .Values.ingress.rateLimit.rpm | quote }}
    nginx.ingress.kubernetes.io/limit-burst-multiplier: {{ .Values.ingress.rateLimit.burstMultiplier | quote }}
    nginx.ingress.kubernetes.io/limit-connections: {{ .Values.ingress.rateLimit.connections | quote }}

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /feedback(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: feedback
                port:
                  number: {{ .Values.service.port }}

{{- end }}