apiVersion: apps/v1
kind: Deployment
metadata:
  name: combat-analysis
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: combat-analysis

  template:
    metadata:
      labels:
        app: combat-analysis

    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
    
      containers:
        - name: combat-analysis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}