{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: combat-analysis

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"

    external-dns.alpha.kubernetes.io/hostname: kubernetes.soulsseeker.com

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # IMPORTANT: only your app path is regex-based
          - path: /analysis(/|$)(.*)
            pathType: ImplementationSpecific

            backend:
              service:
                name: combat-analysis
                port:
                  number: {{ .Values.service.port }}

{{- end }}