{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: combat-analysis

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: kubernetes.soulsseeker.com

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}

  rules:
    - host: {{ .Values.ingress.host }}

      http:
        paths:
          - path: /analysis
            pathType: Prefix

            backend:
              service:
                name: combat-analysis

                port:
                  number: {{ .Values.service.port }}

{{- end }}