apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: soulsseeker-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: combat-analysis
            path: helm/combat-analysis
          - name: feedback
            path: helm/feedback
          - name: vectorizer
            path: helm/vectorizer

  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: app=soulseekerscontainers.azurecr.io/{{name}}
        argocd-image-updater.argoproj.io/app.update-strategy: latest
        argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[a-f0-9]{40}$
        argocd-image-updater.argoproj.io/write-back-method: argocd
        argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/acr-creds
    spec:
      project: default
      source:
        repoURL: https://github.com/Thomas-Slippens/SoulsseekerInfra.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true