replicaCount: 1

image:
  repository: soulseekerscontainers.azurecr.io/feedback
  tag: "0f03346386ab2084fc5eb3a8944bd2f832480f7a"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true

  host: kubernetes.soulsseeker.com

  tls:
    enabled: true
    secretName: feedback-tls

  path: /feedback

# Kubernetes Secret automatically created
# from Azure Key Vault via SecretProviderClass
secretName: kv-secrets

# Inject all Key Vault-backed secrets as env vars
envFrom:
  - secretRef:
      name: kv-secrets

# CSI Secret Store configuration
keyVault:
  enabled: true

  secretProviderClass: feedback-secrets

configMapName: feedback-config