replicaCount: 1

image:
  repository: soulsseekercontainers.azurecr.io/feedback
  tag: "0894db5163661c53beb61e3a48eb4d51bb48fa66"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true

  host: kubernetes.soulsseeker.com

  tls:
    enabled: true
    secretName: feedback-tls

  path: /feedback

# Kubernetes Secret automatically created
# from Azure Key Vault via SecretProviderClass
secretName: kv-secrets

# Inject all Key Vault-backed secrets as env vars
config:
  OpenAI__DeploymentName: "text-embedding-3-small"
  OpenAI__ApiVersion: "2024-12-01"

envFrom:
  - secretRef:
      name: kv-secrets
  - configMapRef:
      name: feedback-config

# CSI Secret Store configuration
keyVault:
  enabled: true

  secretProviderClass: feedback-secrets

configMapName: feedback-config