apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 3e6c1061-eb54-403c-9f8e-e8b92269e252