apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-identity-webhook
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://azure.github.io/azure-workload-identity/charts
    chart: workload-identity-webhook
    targetRevision: 1.2.0

    helm:
      values: |
        azureTenantID: "92b1c82c-10a6-40ec-8b2e-1e63eeb29438"

  destination:
    server: https://kubernetes.default.svc
    namespace: azure-workload-identity-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true