replicaCount: 1

image:
  repository: soulsseekercontainers.azurecr.io/combat-analysis
  tag: "813e3ed0f76e54f9c702ccbb8ea58375bad0303e"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true

  host: kubernetes.soulsseeker.com

  tls:
    enabled: true
    secretName: combat-analysis-tls

  path: /analysis

  rateLimit:
    rpm: 10
    burstMultiplier: 3
    connections: 5

# Kubernetes Secret created automatically
# by the Azure Key Vault SecretProviderClass
secretName: kv-secrets

# Environment variables loaded from Key Vault-backed Kubernetes Secret
config:
  OpenAI__DeploymentName: "gpt-4.1-mini"
  OpenAI__ApiVersion: "2024-10-21"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  ASPNETCORE_URLS: "http://+:8080"
  OpenAI__Endpoint: "https://soulsseekersai.cognitiveservices.azure.com/"
  Cosmos__DatabaseName: "SoulSeekers"
  Cosmos__TacticalReportVectorsContainerName: "SoulSeekersTacticalReportVectors"
  Cosmos__UserTacticalReportContainerName: "SoulSeekersTacticalReports"
  UseManagedIdentity: "false"
  Cosmos__UserPostCombatDialogueContainerName: "SoulSeekersPostCombatDialogue"
  Cosmos__VectorContainer: "SoulSeekersTacticalReportVectors"

envFrom:
  - secretRef:
      name: kv-secrets
  - configMapRef:
      name: combat-analysis-config

# CSI mount configuration
keyVault:
  enabled: true

  secretProviderClass: combat-analysis-secrets

configMapName: combat-analysis-config