replicaCount: 1

image:
  repository: soulseekerscontainers.azurecr.io/combat-analysis
  tag: "0f03346386ab2084fc5eb3a8944bd2f832480f7a"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true

  host: kubernetes.soulsseeker.com

  tls:
    enabled: true
    secretName: combat-analysis-tls

  path: /analysis

# Kubernetes Secret created automatically
# by the Azure Key Vault SecretProviderClass
secretName: kv-secrets

# Environment variables loaded from Key Vault-backed Kubernetes Secret
envFrom:
  - secretRef:
      name: kv-secrets

# CSI mount configuration
keyVault:
  enabled: true

  secretProviderClass: combat-analysis-secrets

configMapName: combat-analysis-config