replicaCount: 1

image:
  repository: soulseekerscontainers.azurecr.io/combat-analysis
  tag: "f66940a97bc0154cfeb4ae1cbaf3c5a179d7a3d3"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: souls.local
  path: /analysis

env:
  - name: DOTNET_RUNNING_IN_CONTAINER
    key: DOTNET_RUNNING_IN_CONTAINER
  - name: ASPNETCORE_URLS
    key: ASPNETCORE_URLS
  - name: OpenAI__Endpoint
    key: OpenAI__Endpoint
  - name: OpenAI__ApiKey
    key: OpenAI__ApiKey
  - name: OpenAI__DeploymentName
    key: OpenAI__DeploymentName
  - name: OpenAI__ApiVersion
    key: OpenAI__ApiVersion
  - name: Cosmos__ConnectionString
    key: Cosmos__ConnectionString
  - name: Cosmos__DatabaseName
    key: Cosmos__DatabaseName
  - name: Cosmos__UserPostCombatDialogueContainerName
    key: Cosmos__UserPostCombatDialogueContainerName
  - name: Cosmos__UserTacticalReportContainerName
    key: Cosmos__UserTacticalReportContainerName
  - name: UseManagedIdentity
    key: UseManagedIdentity

configMapName: combat-analysis-config